site_name: SŠPU
theme:
  name: material
  logo: images/skola-logo.png
extra_css:
  - stylesheets/extra.css
nav:
  - Úvod: index.md
  - Mechatronika:
    - Výukové prezentace: mech_pptx.md
  - Hardware:
    - HW IT4: hw_it4.md