site_name: SŠPU
theme:
  name: material
  logo: images/skola-logo.png
extra_css:
  - stylesheets/extra.css
nav:
  - Úvod: index.md
  - Mechatronika:
    - Výukové prezentace: mech_pptx.md
  - Hardware:
    - HW IT4: hw_it4.md
  - Součástky:
    - Breadboard: soucastky/breadboard.md
    - Rezistory: soucastky/rezistory.md
    - Diody: soucastky/diody.md
    - Kondenzátory: soucastky/kondenzatory.md
    - Tranzistory: soucastky/tranzistory.md
    - Pájení:
        - Nástroje a materiál: soucastky/pajeni_pajky.md
        - Pájení: soucastky/pajeni.md
  - Arduino:
    - DHT11: arduino/dht11.md
    - 7 segment: arduino/sev_seg.md
  - PLC:
    - PLC: plc/plc_popis.md
    - Úkoly: plc/plc_ukoly.md
  - Ostatní:
    - Videa: videa.md